import jsPDF from 'jspdf';
import { format } from 'date-fns';

export const exportConversationToPDF = (messages, metadata = {}) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('GridAssist - Demand Response Chat Export', 20, 20);

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Exported: ${format(new Date(), 'PPpp')}`, 20, 28);

    if (metadata.filename) {
        doc.text(`Data File: ${metadata.filename}`, 20, 34);
    }

    // Messages
    let yPos = 45;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;
    const maxWidth = 170;

    messages.forEach((msg, index) => {
        // Check if we need a new page
        if (yPos > pageHeight - 30) {
            doc.addPage();
            yPos = 20;
        }

        // Message header
        doc.setFontSize(11);
        doc.setFont(undefined, 'bold');
        const sender = msg.sender === 'user' ? 'You' : 'GridAssist';
        const time = format(new Date(msg.timestamp), 'HH:mm');
        doc.text(`${sender} (${time}):`, margin, yPos);

        yPos += 6;

        // Message content
        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        const lines = doc.splitTextToSize(msg.text, maxWidth);

        lines.forEach(line => {
            if (yPos > pageHeight - 30) {
                doc.addPage();
                yPos = 20;
            }
            doc.text(line, margin + 5, yPos);
            yPos += 5;
        });

        yPos += 8; // Spacing between messages
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount}`, margin, pageHeight - 10);
        doc.text('Generated by GridAssist DR Platform', doc.internal.pageSize.width / 2, pageHeight - 10, { align: 'center' });
    }

    // Download
    const filename = `gridassist-chat-${format(new Date(), 'yyyy-MM-dd-HHmm')}.pdf`;
    doc.save(filename);
};

export const exportDataReportToPDF = (data, stats, chartImage) => {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('Load Analysis Report', 20, 20);

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Generated: ${format(new Date(), 'PPpp')}`, 20, 28);

    // Stats section
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Key Statistics', 20, 40);

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    let yPos = 48;

    if (stats) {
        doc.text(`Total Consumption: ${stats.total} ${stats.unit}`, 25, yPos);
        yPos += 6;
        doc.text(`Average Load: ${stats.average} ${stats.unit}`, 25, yPos);
        yPos += 6;
        doc.text(`Peak Load: ${stats.max} ${stats.unit} at ${stats.peakTime}`, 25, yPos);
        yPos += 6;
        doc.text(`Minimum Load: ${stats.min} ${stats.unit}`, 25, yPos);
        yPos += 6;
        doc.text(`Data Points: ${stats.count}`, 25, yPos);
    }

    // Chart (if provided as base64 image)
    if (chartImage) {
        yPos += 15;
        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.text('Load Profile', 20, yPos);
        yPos += 8;

        try {
            doc.addImage(chartImage, 'PNG', 20, yPos, 170, 80);
        } catch (e) {
            console.error('Failed to add chart image:', e);
        }
    }

    const filename = `load-analysis-${format(new Date(), 'yyyy-MM-dd')}.pdf`;
    doc.save(filename);
};
